// Package swgui provide a http FileSystem handler for swagger UI interface
//
// File `bindata_assetfs.go` is generated by go-bindata-assetfs (https://github.com/elazarl/go-bindata-assetfs) tool,
// which help to embed all static files into a go source file.
//
// How to generate file:
//
// NOTE:
//  * File `bindata_assetfs.go` ONLY need to re-generate file again when we update swagger-ui (swagger/ui/static)
//
// 1. Install tools:
//
//      go get -u github.com/jteeuwen/go-bindata/...
//      go get -u github.com/elazarl/go-bindata-assetfs/...
//
// 2. Generate file:
//
// At root folder, run command:
//
//      go-bindata-assetfs -pkg=swgui static/...
//      gofmt -w bindata_assetfs.go
//
// Or just run: `go generate`
//
// Enjoy it ;)
//
package swgui
